# Generated by Django 4.2.4 on 2024-01-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
