# Generated by Django 3.2.7 on 2024-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0004_auto_20240123_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
