# Generated by Django 4.2.4 on 2024-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0005_auto_20240123_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_images/'),
        ),
    ]
