# Generated by Django 4.2.4 on 2024-01-24 10:23
from datetime import datetime, timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0006_inquiry_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime(2022, 1, 1, 0, 0, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
    ]

