# Generated by Django 4.2.4 on 2024-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0007_inquiry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
    ]
