# Generated by Django 4.2.4 on 2024-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0008_inquiry_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='shiji_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
