# Generated by Django 4.2.4 on 2024-01-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0009_inquiry_shiji_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='title',
            new_name='purpose',
        ),
    ]
