# Generated by Django 4.2.4 on 2024-01-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0010_rename_title_inquiry_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='shiji_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
