# Generated by Django 4.2.4 on 2024-01-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0011_inquiry_shiji_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='possibility',
            field=models.CharField(blank=True, choices=[('採用', '採用'), ('不採用', '不採用')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reuse',
            field=models.CharField(blank=True, choices=[('未', '未'), ('済', '済')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='genre',
            field=models.ManyToManyField(blank=True, to='design_search.genre'),
        ),
    ]
