# Generated by Django 4.2.4 on 2024-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0012_genre_inquiry_possibility_inquiry_reuse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='genre',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
