# Generated by Django 4.2.4 on 2024-01-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0013_remove_inquiry_genre_inquiry_is_checked_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='possibility',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='reuse',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='selected_patterns',
            field=models.ManyToManyField(blank=True, to='design_search.pattern'),
        ),
    ]
