# Generated by Django 4.2.4 on 2024-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0014_pattern_remove_inquiry_is_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='selected_patterns',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='possibility',
            field=models.CharField(blank=True, choices=[('採用', '採用'), ('不採用', '不採用')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reuse',
            field=models.CharField(blank=True, choices=[('未', '未'), ('済', '済')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
