# Generated by Django 4.2.4 on 2024-01-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0015_remove_inquiry_selected_patterns_inquiry_possibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='fruits',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
