# Generated by Django 4.2.4 on 2024-01-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_search', '0016_inquiry_fruits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='fruits',
            new_name='genres',
        ),
    ]
